<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ServiceObject" nsURI="http://defaultname/1.0" nsPrefix="defaultname">
  <eClassifiers xsi:type="ecore:EClass" name="SLA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="1" eType="#//ServiceObject">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attributeWildcard"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceObject" eType="#//ServiceObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//ServiceContractingPartners" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceThirdPartners" lowerBound="1"
        upperBound="-1" eType="#//ServcieThirdPartners" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SLO" lowerBound="1" upperBound="-1"
        eType="#//SLO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceContractingPartners"
        lowerBound="1" upperBound="-1" eType="#//ServiceContractingPartners" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataObject" upperBound="-1"
        eType="#//DataObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Functionality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Functionality" lowerBound="1"
        upperBound="-1" eType="#//Functionality" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceObject" lowerBound="1"
        upperBound="-1" eType="#//DataObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Server" lowerBound="1"
        upperBound="-1" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceContractingPartners"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServcieThirdPartners"/>
  <eClassifiers xsi:type="ecore:EClass" name="SLO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Obligation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Penalty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Obligation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Penalty" lowerBound="1"
        upperBound="-1" eType="#//Penalty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Obligation" lowerBound="1"
        upperBound="-1" eType="#//Obligation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functionality">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//DataObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConstraintParameter" upperBound="-1"
        eType="#//ConstraintParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="#//DataConstraint #//ConstraintParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//DataOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataAdministrator" lowerBound="1"
        eType="#//DataAdministrator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataConstraint" lowerBound="1"
        upperBound="-1" eType="#//DataConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataLossPenalty" lowerBound="1"
        upperBound="-1" eType="#//DataLossPenalty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataOwner" lowerBound="1"
        eType="#//DataOwner" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Servers" lowerBound="1"
        upperBound="-1" eType="#//Server"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintParameter" eSuperTypes="#//NegotiableConstraintParameter #//Criterion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Criteria" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParameterId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Criterion" lowerBound="1"
        upperBound="-1" eType="#//Criterion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Criteria">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Clause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="Obligation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//Penalty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Object" lowerBound="1"
        upperBound="-1" eType="#//Object" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Condition" lowerBound="1"
        upperBound="-1" eType="#//Condition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Penalty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Obligation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataOwner"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAdministrator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataLossPenalty" eSuperTypes="#//Penalty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//Obligation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataLocationConstraint" eSuperTypes="#//DataConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSharingConstraint" eSuperTypes="#//DataConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Server"/>
  <eClassifiers xsi:type="ecore:EClass" name="NegotiableConstraintParameter" eSuperTypes="#//Criteria #//ConstraintParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="NonNegotiableConstraints" eSuperTypes="#//Criteria #//ConstraintParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="Criterion"/>
</ecore:EPackage>
